2
[root@localhost git]# git push origin main
Username for 'https://github.com': kgsharadhaskill-edu
Password for 'https://kgsharadhaskill-edu@github.com':
To https://github.com/kgsharadhaskill-edu/testkgpath.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/kgsharadhaskill-edu/testkgpath.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first merge the remote changes (e.g.,
hint: 'git pull') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
[root@localhost git]# git push origin main
Username for 'https://github.com': kgsharadhaskill-edu
Password for 'https://kgsharadhaskill-edu@github.com':
fatal: Authentication failed for 'https://github.com/kgsharadhaskill-edu/testkgpath.git/'
[root@localhost git]# git add Jenkinsfile
[root@localhost git]# git status
no changes added to commit (use "git add" and/or "git commit -a")
[root@localhost git]# git merge origin/main
Already up-to-date.
[root@localhost git]# git push origin main
Username for 'https://github.com': kgsharadhaskill-edu
Password for 'https://kgsharadhaskill-edu@github.com':
To https://github.com/kgsharadhaskill-edu/testkgpath.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/kgsharadhaskill-edu/testkgpath.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first merge the remote changes (e.g.,
hint: 'git pull') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
[root@localhost git]# git branch
* main
  master
 for your changes. Lines starting